# docs/src/orchid/resources/config.yml
site:
  about:
    siteName: Kotlin设计模式
    siteDescription: 用kotlin实现设计模式
Editorial:
  primaryColor: '#DE9149'
  social:
    github: 'xmmmmmovo/DesignPatterns'
  metaComponents: # this is the replacement for the deprecated automatic search addition
    - type: 'orchidSearch'
  menu:
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
    - type: 'page'
      itemId: 'Changelog'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'
kotlindoc:
  sourceDirs:
    - './../../../../src/main/kotlin'
  sourcePages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'kotlindoc'
        itemTitleType: 'SIGNATURE'
        includeItems: true